import Head from "next/head";
import styled from "styled-components";
import Countdown from "../components/Countdown";

import "react-datepicker/dist/react-datepicker.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dream Day Wedding Planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PufferPageTop />
        <Countdown />
      </main>
    </div>
  );
}

const PufferPageTop = styled.div`
  height: 15vh;
`;
